// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtg92xU9m1fkItkgFG_Ex8YEwgF9GI0Vo',
    appId: '1:614177818467:web:e19f0152b53e3fa1c0f556',
    messagingSenderId: '614177818467',
    projectId: 'tbc-free-b297d',
    authDomain: 'tbc-free-b297d.firebaseapp.com',
    storageBucket: 'tbc-free-b297d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCllxvlsS5-8Xa1MKoydk_t1LJ6lQekn-0',
    appId: '1:614177818467:android:be98d9dbeefc795fc0f556',
    messagingSenderId: '614177818467',
    projectId: 'tbc-free-b297d',
    storageBucket: 'tbc-free-b297d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLJ7M9HmEMK9viQFDlmWXXfPdGrnCqx4',
    appId: '1:614177818467:ios:d0061a5cc0995ea4c0f556',
    messagingSenderId: '614177818467',
    projectId: 'tbc-free-b297d',
    storageBucket: 'tbc-free-b297d.appspot.com',
    iosBundleId: 'com.example.tbcApp',
  );
}
